apiVersion: v1
kind: Service
metadata:
  name: service-two
  labels:
    app: service-two
spec:
  type: ClusterIP
  selector:
    app: service-two
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
