name: "Get changed files and deployments"
description: "An action to get changed deployments in a pull request"
inputs:
  pr_number:
    description: "Pull request number"
    required: true
  token:
    description: "GitHub token"
    required: true
outputs:
  changed-deployments-base64:
    description: "List of changed deployments in the PR, encoded in base64"
    value: ${{ steps.changed-deployments.outputs.CHANGED_DEPLOYMENTS }}
runs:
  using: composite
  steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Get list of changed files
      shell: bash
      run: |
        {
            echo 'CHANGED_FILES<<EOF'
            gh pr diff ${{ inputs.pr_number }} --name-only
            echo EOF
        } >> "$GITHUB_ENV"
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Identify changed deployments
      id: changed-deployments
      shell: bash
      run: |
        echo "CHANGED_DEPLOYMENTS=$(echo "${CHANGED_FILES}" | grep deployments/ | cut -d '/' -f 2 | sort -u | uniq | base64)" >> $GITHUB_OUTPUT
