apiVersion: v1
kind: Service
metadata:
  name: service-one
  labels:
    app: service-one
spec:
  type: ClusterIP
  selector:
    app: service-one
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
