name: Build k8s manifests for the chosen environment with Kustomize

on:
  issue_comment:
    types: [created]

jobs:
  kustomize_selected_env:
    if: startsWith(github.event.comment.body, '/build') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    steps:
    - name: Check out the code
      uses: actions/checkout@v4
    
    - name: Print branch name
      run: |
        echo "Branch: ${{ github.event.issue.pull_request.head.ref }}"

    - name: Get pull request number
      run: |
        echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

    - name: Extract the environment from the comment
      run: |
        COMMENT_ENV=$(echo "${{ github.event.comment.body }}" | awk '{print $2}')
        echo "COMMENT_ENV=$COMMENT_ENV" >> $GITHUB_ENV

    - name: Check if the environment is supported
      id: check_env
      run: |
        if [[ "$COMMENT_ENV" == "dev" || "$COMMENT_ENV" == "staging" || "$COMMENT_ENV" == "prod" ]]; then
          echo "SUPPORTED_ENV=true" >> $GITHUB_OUTPUT
        else
          echo "SUPPORTED_ENV=false" >> $GITHUB_OUTPUT
        fi

    - name: Comment on unsupported environment
      if: steps.check_env.outputs.SUPPORTED_ENV == 'false'
      run: |
        gh pr comment $PR_NUMBER --body "The environment '$COMMENT_ENV' is unsupported. Please choose one of the following: dev, staging, prod.
        
        Example: /build dev"

        exit 1
    
    - name: Get list of changed deployments
      id: list_changes
      uses: ./.github/actions/list-changed-deployments
      with:
        pr_number: ${{ github.event.issue.number }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check if all edited deployments have the chosen overlay
      run: |
        CHANGED_APPS=$(echo "${{ steps.list_changes.outputs.changed-deployments-base64 }}" | base64 --decode)
        echo "$CHANGED_APPS" | while IFS= read -r app; do
          if [ ! -d "deployments/$app/overlays/$COMMENT_ENV" ]; then
            gh pr comment $PR_NUMBER --body ":x: The deployment $app does not have '$COMMENT_ENV' overlay."
            exit 1
          fi
        done

    - name: Download and install Kustomize v5.4.2
      run: |
        curl -Lo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.4.2/kustomize_v5.4.2_linux_amd64.tar.gz
        tar -xzf kustomize.tar.gz
        sudo mv kustomize /usr/local/bin/
        rm kustomize.tar.gz

    - name: Run Kustomize build for edited deployments and selected environment
      run: |
        CHANGED_APPS=$(echo "${{ steps.list_changes.outputs.changed-deployments-base64 }}" | base64 --decode)
        echo "$CHANGED_APPS" | while IFS= read -r app; do
          KUSTOMIZE_OUTPUT=$(kustomize build deployments/$app/overlays/$COMMENT_ENV)
          gh pr comment $PR_NUMBER --body "Deployment $app - $COMMENT_ENV:
          \`\`\`yaml
          $KUSTOMIZE_OUTPUT
          \`\`\`"
        done
