name: Build k8s manifests for the chosen environment with Kustomize

on:
  issue_comment:
    types: [created]

jobs:
  kustomize_selected_env:
    if: startsWith(github.event.comment.body, '/build') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    steps:
    - name: Check out the code
      uses: actions/checkout@v4
     
    - name: Get pull request number
      run: |
        echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

    - name: Extract the environment from the comment
      run: |
        COMMENT_ENV=$(echo "${{ github.event.comment.body }}" | awk '{print $2}')
        echo "COMMENT_ENV=$COMMENT_ENV" >> $GITHUB_ENV

    - name: Check if the environment is supported
      id: check_env
      run: |
        if [[ "$COMMENT_ENV" == "dev" || "$COMMENT_ENV" == "staging" || "$COMMENT_ENV" == "prod" ]]; then
          echo "SUPPORTED_ENV=true" >> $GITHUB_OUTPUT
        else
          echo "SUPPORTED_ENV=false" >> $GITHUB_OUTPUT
        fi

    - name: Comment on unsupported environment
      if: steps.check_env.outputs.SUPPORTED_ENV == 'false'
      run: |
        gh pr comment $PR_NUMBER --body "The environment '$COMMENT_ENV' is unsupported. Please choose one of the following: dev, staging, prod.
        
        Example: /build dev"
    
    - name: Download and install Kustomize v5.4.2
      if: steps.check_env.outputs.SUPPORTED_ENV == 'true'
      run: |
        curl -Lo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.4.2/kustomize_v5.4.2_linux_amd64.tar.gz
        tar -xzf kustomize.tar.gz
        sudo mv kustomize /usr/local/bin/
        rm kustomize.tar.gz

    - name: Run Kustomize build for the selected environment
      if: steps.check_env.outputs.SUPPORTED_ENV == 'true'
      run: |
        {
            echo 'KUSTOMIZE_OUTPUT<<EOF'
            kustomize build deployments/service-one/overlays/$COMMENT_ENV
            echo EOF
        } >> "$GITHUB_ENV"

    - name: Comment build success
      if: steps.check_env.outputs.SUPPORTED_ENV == 'true'
      run: |
        gh pr comment $PR_NUMBER --body "Kustomize build for the environment'$COMMENT_ENV':
        \`\`\`yaml
        $KUSTOMIZE_OUTPUT
        \`\`\`"
 