name: Comment with changed deployments

on:
  issue_comment:
    types: [created]

jobs:
  comment_changed_apps:
    if: startsWith(github.event.comment.body, '/list') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    steps:
    - name: Check out the code
      uses: actions/checkout@v4
     
    - name: Get pull request number
      run: |
        echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
  
    - name: Get list of changes
      id: list_changes
      uses: ./.github/actions/list-changed-deployments
      with:
        pr_number: ${{ github.event.issue.number }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment changed deployments on the PR
      run: |
        CHANGED_APPS=$(echo "${{ steps.list_changes.outputs.changed-deployments-base64 }}" | base64 --decode)
        gh pr comment $PR_NUMBER --body "List of changed deployments:
        $CHANGED_APPS"
