name: List Changed Files

on:
  issue_comment:
    types: [created]

jobs:
  list_changed_files:
    if: startsWith(github.event.comment.body, '/list') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Say hello world
      run: |
        echo "Hello world from Pull Request!"
     
    - name: Get pull request number
      run: |
        echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
  
    - name: Get list of changed files
      run: |
        {
            echo 'CHANGED_FILES<<EOF'
            gh pr diff $PR_NUMBER --name-only
            echo EOF
        } >> "$GITHUB_ENV"
   
    - name: Comment on the PR
      run: |
        gh pr comment $PR_NUMBER --body "List of changed files:
            ${CHANGED_FILES}"

    - name: Identify changed applications
      run: |
        changed_apps=$(echo "${CHANGED_FILES}" | grep -Eo '^deployments/[^/]+/overlays/'"${COMMENT_ENV}" | cut -d '/' -f 2 | sort -u)
        echo $changed_apps    
        echo "CHANGED_APPS=$changed_apps" >> $GITHUB_ENV
